# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get current branch
        id: get_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Print Branch Name
        run: echo "Building on branch: $BRANCH_NAME"
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
