# This workflow will build a Swift project dynamically based on the current branch

name: Swift

on:
  push:
    branches:
      - "**"  # Matches all branches
  pull_request:
    branches:
      - "**"  # Triggers on PRs to any branch

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: swift build -v
        
      - name: Run tests
        run: swift test -v
